#ifndef	_EXECUTOR_OP_H_
#define	_EXECUTOR_OP_H_

#define EXEC_OP_M3_CONV2D_Q7        1
#define EXEC_OP_M3_AVPOOL2D_Q7    2
#define EXEC_OP_M3_RELU_Q7             3
#define EXEC_OP_M3_PW_CONV2D_Q7  4
#define EXEC_OP_M3_DS_CONV2D_Q7  5
#define EXEC_OP_M3_DS_CONV2D_LAYER2_Q7 6
#define EXEC_OP_M3_DS_CONV2D_SB_LAYER3_Q7  7
#define EXEC_OP_M3_PW_DS_CONV2D_LAYER4AND5_Q7 8
#define EXEC_OP_M3_CONCAT_HEIGHT_Q7    9
#define EXEC_OP_M3_SIGMOID_Q7    10
#define EXEC_OP_M3_MAXPOOL_Q7    11
#define EXEC_OP_M3_FULLY_CONNECTED_Q7    12
#define EXEC_OP_M3_ADD_Q7   13


//DSP operation starts here

#define EXEC_OP_DSP_CHW_2X2_CONV2D_RELU_AVGPOOL_Q7     64
#define EXEC_OP_DSP_CHW_3X3_CONV2D_RELU_AVGPOOL_Q7     65
#define EXEC_OP_DSP_CHW_PW_CONV2D_Q7                                 66
#define EXEC_OP_DSP_HWC_PW_CONV2D_Q7                                 67
#define EXEC_OP_DSP_HWC_PW_CONV2D_Q7_FAST                       68
#define EXEC_OP_DSP_CHW_3X3_CONV2D_STRIDE2_PAD0_RELU             69
#define EXEC_OP_DSP_CHW_3X3_CONV2D_STRIDE1_PAD0_RELU             70
#define EXEC_OP_DSP_CHW_2X2_CONV2D_STRIDE2_PAD0_RELU             71
#define EXEC_OP_DSP_HWC_PW_CONV2D_Q7_INOUT_DONT_FIT              72
#define EXEC_OP_DSP_HWC_PW_CONV2D_Q7_WEIGHT_DONT_FIT          73
#define EXEC_OP_DSP_DS_CHW_2X2_CONV2D_STRIDE2_PAD0_RELU     74
#define EXEC_OP_DSP_DS_CHW_3X3_CONV2D_STRIDE2_PAD0_RELU     75
#define EXEC_OP_DSP_DS_CHW_3X3_CONV2D_STRIDE1_PAD0_RELU      76
#define EXEC_OP_DSP_DS_CHW_3X3_CONV2D_STRIDE1_PAD0_RELU_INPLACE 77
#define EXEC_OP_DSP_DS_CHW_3X3_CONV2D_STRIDE2_PAD0_RELU_INPLACE 78
#define EXEC_OP_DSP_CHW_3X3_CONV2D_STRIDE2_PAD0_RELU_HWC         79


//DSP math function acceleration operations starts here
#define EXEC_OP_DSP_MATH_FFT     101
#define EXEC_OP_DSP_MATH_SQRT    102
#define EXEC_OP_DSP_MATH_EXP     103
#define EXEC_OP_DSP_MATH_LOG     104

#define EXEC_OP_DSP_MATH_OPT_START     EXEC_OP_DSP_MATH_FFT
#define EXEC_OP_DSP_MATH_OPT_END       EXEC_OP_DSP_MATH_LOG







#endif /*_EXECUTOR_OP_H_*/
